// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4473.PowerUp.subsystems;

import org.usfirst.frc4473.PowerUp.Robot;
import org.usfirst.frc4473.PowerUp.RobotMap;
import org.usfirst.frc4473.PowerUp.commands.driveTank;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.Sendable;
import edu.wpi.first.wpilibj.command.Subsystem;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class drive extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	public int counter = 0;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final DifferentialDrive roboDrive = RobotMap.driveroboDrive;
    
    public double dLRawDriveSpeed;
    public double dRRawDriveSpeed;
    
    public boolean IsAuto = false; 
    public double EncRatio = 1.0;
    
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public void driveStraightForward() {
    	driveStraight(1);
    }
    public void driveStraightReverse() {
    	driveStraight(-1);
    }
    private void driveStraight(int direction) {
    	double baseSpeed = 0.6 * direction;
    	
    	// TODO: Figure out how to compensate for uneven motors
    	if(Robot.driveEncLeft.getRate() != 0.0)// && Math.floorMod(counter, 5)==0)
    	{
    		EncRatio = Math.abs(Robot.driveEncRight.getRate() / Robot.driveEncLeft.getRate());
    		//EncRatio = Math.abs(Robot.driveEncLeft.getRate() / Robot.driveEncRight.getRate());
    	}
    	SmartDashboard.putNumber("EncoderRatio", EncRatio);
    	
    	roboDrive.tankDrive(baseSpeed, baseSpeed);
    }
    
    public void driveAuto()
    {
    	SmartDashboard.putString("DriveCounter", (Integer.toString(counter++)) );
//    	if(Robot.driveEncLeft.getRate() != 0.0)// && Math.floorMod(counter, 5)==0)
//    	{
//    		EncRatio = Math.abs(Robot.driveEncRight.getRate() / Robot.driveEncLeft.getRate());
//    		//EncRatio = Math.abs(Robot.driveEncLeft.getRate() / Robot.driveEncRight.getRate());
//    	}
//    	SmartDashboard.putNumber("EncoderRatio", EncRatio);
//    	roboDrive.tankDrive(0.6, 0.6);
    }
    public void takeJoystickInput(Joystick leftstick, Joystick rightstick) 
    {
    	roboDrive.tankDrive(leftstick.getRawAxis(1), rightstick.getRawAxis(1));
    }
    public void stop() 
    {
    	roboDrive.tankDrive(0, 0);
    }

    public void initDefaultCommand() {
    	setDefaultCommand(new driveTank());
    }
    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

